import { FormEvent, useState } from "react";
import { ArrowUpRight, Check, Clock3 } from "lucide-react";
import { Link } from "wouter";
import { business, serviceItems } from "@/lib/site";
import { AmbientOrb, PageHero, SectionLabel } from "@/components/Primitives";

export default function Appointment() {
  const [submitted, setSubmitted] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true); };
  return <div className="page appointment-page"><PageHero eyebrow="Salon Oval / 06" title={<><span>Your next</span><em>look starts here.</em></>} intro="Send an enquiry and the salon team can follow up directly. This form does not confirm an appointment or show live availability." /><section className="appointment-section section-cream"><div className="container appointment-grid"><div className="appointment-aside"><SectionLabel index="01">Appointment enquiry</SectionLabel><h2>Make room<br /><em>for a new you.</em></h2><p>Share a few details and the salon can respond with the next available step.</p><div className="appointment-detail"><Clock3 size={16} /><span>Preferred date and time are enquiry fields only.</span></div><div className="appointment-detail"><ArrowUpRight size={16} /><a href={`tel:${business.phone.replaceAll(" ", "")}`}>{business.phone}</a></div></div>{submitted ? <div className="form-success"><div className="success-icon"><Check size={20} /></div><p className="eyebrow">Enquiry received</p><h3>Thank you.</h3><p>Your appointment request has been received. The salon team can follow up directly to confirm details and availability.</p><div className="form-success-actions"><Link href="/" className="oval-button">Back home <ArrowUpRight size={15} /></Link><button type="button" className="text-link" onClick={() => setSubmitted(false)}>Send another enquiry</button></div></div> : <form className="appointment-form" onSubmit={submit}><div className="form-row"><label>Full name<input name="name" required placeholder="Your name" /></label><label>Phone number<input name="phone" type="tel" required placeholder="+94 ..." /></label></div><div className="form-row"><label>Email<input name="email" type="email" placeholder="you@example.com" /></label><label>Service<select name="service" defaultValue=""><option value="" disabled>Select a direction</option>{serviceItems.map((service) => <option key={service.number} value={service.label}>{service.label}</option>)}</select></label></div><div className="form-row"><label>Preferred date<input name="date" type="date" /></label><label>Preferred time<input name="time" type="time" /></label></div><label>Message<textarea name="message" rows={5} placeholder="Tell us what you are imagining..." /></label><div className="form-submit"><button type="submit" className="oval-button">Request appointment <ArrowUpRight size={15} /></button><span>By sending this enquiry, you are asking the salon to follow up. No appointment is confirmed here.</span></div></form>}</div></section></div>;
}
